<footer class="footer">
    <div class="footer-section">
        <h2>TechNova</h2>
        <p>TechNova Solutions offers innovative IT services since 2004 and seeks passionate talent to join its growth-focused team.</p>
    </div>
    <div class="footer-section">
        <h3>Pages</h3>
        <ul>
            <li><a href="index.php" class="webpages">Home</a></li>
            <li><a href="jobs.php" class="webpages">Jobs</a></li>
            <li><a href="apply.php" class="webpages">Apply</a></li>
            <li><a href="manager_login.php" class="webpages">Management</a></li>
            <li><a href="enhancements.php" class="webpages">Enhancements</a></li>
            <li><a href="about.php" class="webpages">About us</a></li>
        </ul>
    </div>
    <div class="footer-section">
        <h3>Developers</h3>
        <ul>
            <li>Alexander</li>
            <li>Jashandeep</li>
            <li>Harri</li>
            <li>Sathil</li>
        </ul>
    </div>
    <div class="footer-bottom">
        <p>&copy;2025 TechNova All Rights Reserved</p>
        <div class="footer-bottom-links">
            <p><a href="https://github.com/105753341/COS10026-Assignment-1" class="proj_links" target="_blank">Github</a></p>
            <p><a href="https://cos10026-web-project.atlassian.net/jira/software/projects/T2WPA/boards/3?atlOrigin=eyJpIjoiNTgyNzczZjE5NzBmNDIxMDk1NmQ1MDI5MzRlMDE5NWMiLCJwIjoiaiJ9" class="proj_links" target="_blank">Jira</a></p>
        </div>
    </div>
</footer>