<header>
    <a href="index.php"><img src="images/logo_cropped.png" alt="Company Logo"></a>
    <nav>
        <a href="index.php">Home Page</a> 
        <a href="jobs.php">Job Descriptions</a> 
        <a href="manager_login.php">Management</a>
        <a href="apply.php">Application Page</a>
        <a href="about.php">Group details</a>
        <a href="mailto:info@technova.com.au">&#128231;</a> 
        </nav>
        <hr>
</header>